# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-09 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='file',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
