# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-09 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_list_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
